### ISSUE TITLE
Create a GET request

### ISSUE THREAD

**Issue by phonicmouse** [interactive-matter/HTTPClient#17]
@interactive-matter @Apollon77 
how to do that?
Please help me..

**Comment by Apollon77** [comment]
Very simple:

  HTTPClient client("IP", PORT);
  //client.debug(1);

  // FILE is the return STREAM type of the HTTPClient
  char Uri[255]="...";
  FILE\* result = client.getURI(Uri);

  int returnCode = client.getLastReturnCode();

  if (returnCode==NULL) {
    //Error
  }

  if (result!=NULL) {
    int c;
    response="";
    while ((c = fgetc(result)) != EOF) {
      response+=(char) c;
      //Serial.print((char) c);
    }
    if (ferror(result)) {
      //error
    }

```
//Serial.println("");
client.closeStream(result);  // this is very important -- be sure to close the STREAM
```

  }

**Comment by phonicmouse** [comment]
thanks.

**Comment by phonicmouse** [comment]
@Apollon77 
only one thing...where do you get the response char?

**Comment by Apollon77** [comment]
response is simply declared as String

**Comment by phonicmouse** [comment]
ok thanks
;)
